version: "3.6"
services:
  mantisbt:
    image: xlrl/mantisbt:2.25.2
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - postgres
    volumes:
      - ./:/var/www/html/plugins/ToDoLists
      - ./config:/var/www/html/config
    restart: unless-stopped
  mysql:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    volumes:
      - mysql:/var/lib/mysql
  postgres:
    image: postgres:12.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=mantisbt
      - POSTGRES_DB=bugtracker
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  mysql:
  postgres:
